'use client';

import { useState, useEffect, useMemo } from 'react';
import Sidebar from '../components/Sidebar';
import InfraMap from '../components/InfraMap';
import HealthPanel from '../components/HealthPanel';
import CostPanel from '../components/CostPanel';
import ChatPanel from '../components/ChatPanel';
import AlertFeed from '../components/AlertFeed';
import { fetchResources, fetchMetrics, fetchCostData, fetchAlerts } from '../lib/api';

export default function Dashboard() {
    const [resources, setResources] = useState(null);
    const [connections, setConnections] = useState(null);
    const [metrics, setMetrics] = useState(null);
    const [costData, setCostData] = useState(null);
    const [alerts, setAlerts] = useState(null);
    const [loading, setLoading] = useState(true);
    const [showSkyMind, setShowSkyMind] = useState(true);

    // CDK stack prefixes — ALL resources generated by skymind-stack.js and
    // github-oidc-stack.js are named with one of these prefixes.
    const CDK_STACK_PREFIXES = ['skymindtier1stack-', 'skymindgithuboidcstack-'];

    const isSkyMindResource = (r) => {
        // 1. Trust backend tag if available
        if (r.skymind !== undefined) return r.skymind;
        // 2. Match on CDK stack name prefix (reliable for ALL CDK-generated resources)
        const name = (r.name || '').toLowerCase();
        if (CDK_STACK_PREFIXES.some(prefix => name.startsWith(prefix))) return true;
        // 3. API Gateway uses a custom display name set in the CDK code
        if (name === 'skymind dashboard api') return true;
        return false;
    };

    // Build accurate connections from actual CDK architecture relationships.
    // This maps the real wiring defined in skymind-stack.js (Lambda → DynamoDB/S3,
    // API Gateway → Lambda, etc.) by recognising construct names inside
    // the auto-generated AWS resource names.
    const buildArchitectureConnections = (resourceList) => {
        const conns = [];
        const added = new Set();
        const add = (sourceId, targetId) => {
            const key = `${sourceId}->${targetId}`;
            if (!added.has(key) && sourceId !== targetId) {
                added.add(key);
                conns.push({ source: sourceId, target: targetId });
            }
        };

        // Helper: find resources whose lowered name contains a keyword
        const findByKeyword = (keyword) =>
            resourceList.filter(r => r.name.toLowerCase().includes(keyword.toLowerCase()));

        // API Gateway → Lambda integrations (from CDK addMethod calls)
        const apiGWs = findByKeyword('SkyMind Dashboard API');
        // These Lambdas are wired to API Gateway in the CDK stack
        const apiLambdaKeywords = ['scannerfunction', 'metricsreaderfunction', 'alertsfunction', 'costfunction', 'chatfunction'];
        apiGWs.forEach(gw => {
            apiLambdaKeywords.forEach(kw => {
                findByKeyword(kw).forEach(fn => add(gw.id, fn.id));
            });
        });

        // Lambda → DynamoDB (from CDK grantReadWriteData / grantReadData)
        const resourcesTables = findByKeyword('resourcestable');
        const metricsTables  = findByKeyword('metricstable');
        const alertsTables   = findByKeyword('alertstable');
        const dataLakes      = findByKeyword('skyminddatalake');

        const connectLambda = (keyword, targets) => {
            findByKeyword(keyword).forEach(fn => {
                targets.forEach(tList => tList.forEach(t => add(fn.id, t.id)));
            });
        };

        // Exact CDK wiring from skymind-stack.js:
        connectLambda('scannerfunction',       [resourcesTables]);
        connectLambda('metricsfunction',        [resourcesTables, metricsTables]);
        connectLambda('analyzerfunction',       [metricsTables, alertsTables]);
        connectLambda('healerfunction',         [alertsTables]);
        connectLambda('chatfunction',           [resourcesTables, alertsTables]);
        // Data lake S3 connections (logical — scanner writes data there)
        connectLambda('scannerfunction',        [dataLakes]);

        return conns;
    };

    useEffect(() => {
        async function loadData() {
            try {
                const resData = await fetchResources();
                const realResources = resData.resources || [];
                setConnections(resData.connections);

                const [metricsData, cost, alertsData] = await Promise.all([
                    fetchMetrics(realResources),
                    fetchCostData(),
                    fetchAlerts(),
                ]);

                // Upgrade resource statuses based on real metrics
                const metricsLookup = (metricsData && typeof metricsData === 'object' && !metricsData.message) ? metricsData : {};
                const enrichedResources = realResources.map(r => {
                    const m = metricsLookup[r.id];
                    if (!m) return r;
                    let status = r.status || 'healthy';
                    if (m.latency > 500) status = 'warning';
                    if (m.latency > 2000) status = 'critical';
                    if (r.type === 'Lambda' && m.duration > 1000) status = status === 'critical' ? 'critical' : 'warning';
                    if (m.errors > 0 && m.invocations > 0 && (m.errors / m.invocations) > 0.05) status = 'warning';
                    return { ...r, status };
                });

                setResources(enrichedResources);
                setMetrics(metricsData);
                setCostData(cost);
                setAlerts(alertsData);

            } catch (err) {
                console.error('Failed to load dashboard data:', err);
            } finally {
                setLoading(false);
            }
        }
        loadData();

        const interval = setInterval(loadData, 30000);
        return () => clearInterval(interval);
    }, []);

    const filteredResources = useMemo(() => {
        if (!resources) return null;
        return resources.filter(r => showSkyMind || !isSkyMindResource(r));
    }, [resources, showSkyMind]);

    const displayConnections = useMemo(() => {
        if (!filteredResources) return null;
        // 1. Use real connections from API if available
        if (connections && connections.length > 0) {
            return connections.filter(c =>
                filteredResources.find(r => r.id === c.source) &&
                filteredResources.find(r => r.id === c.target)
            );
        }
        // 2. Deterministic fallback: build connections from known CDK architecture
        return buildArchitectureConnections(filteredResources);
    }, [filteredResources, connections]);

    const stats = filteredResources ? {
        total: filteredResources.length,
        healthy: filteredResources.filter(r => r.status === 'healthy').length,
        warnings: filteredResources.filter(r => r.status === 'warning').length,
        critical: filteredResources.filter(r => r.status === 'critical').length,
    } : {};

    if (loading) {
        return (
            <div className="app-container">
                <Sidebar stats={{}} />
                <main className="main-content" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <div style={{ textAlign: 'center' }}>
                        <div style={{
                            fontSize: '3rem',
                            marginBottom: '16px',
                            animation: 'pulse-dot 2s ease-in-out infinite',
                        }}>🧠</div>
                        <h2 style={{
                            background: 'var(--accent-gradient)',
                            WebkitBackgroundClip: 'text',
                            WebkitTextFillColor: 'transparent',
                            fontSize: '1.5rem',
                            fontWeight: 700,
                        }}>SkyMind is Loading...</h2>
                        <p style={{ color: 'var(--text-tertiary)', marginTop: '8px', fontSize: '0.85rem' }}>
                            Scanning your infrastructure
                        </p>
                    </div>
                </main>
            </div>
        );
    }

    return (
        <div className="app-container">
            <Sidebar stats={stats} />

            <main className="main-content" id="dashboard">
                {/* Header */}
                <header className="dashboard-header">
                    <h1>Infrastructure Overview</h1>
                    <div className="header-status" style={{ display: 'flex', gap: '15px', alignItems: 'center' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'rgba(255,255,255,0.05)', padding: '6px 12px', borderRadius: '20px' }}>
                            <label style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', cursor: 'pointer' }}>
                                <input
                                    type="checkbox"
                                    checked={showSkyMind}
                                    onChange={(e) => setShowSkyMind(e.target.checked)}
                                    style={{ marginRight: '6px' }}
                                />
                                Show SkyMind Infrastructure
                            </label>
                        </div>
                        <div className="status-dot" />
                        <span>Live • {stats.total} resources monitored • us-east-1</span>
                    </div>
                </header>

                {/* Dashboard Grid */}
                <div className="dashboard-grid">
                    {/* Left Column: Infra Map + Cost */}
                    <div className="grid-column">
                        <InfraMap resources={filteredResources} connections={displayConnections} />
                        <CostPanel costData={costData} resources={filteredResources} metrics={metrics} />
                    </div>

                    {/* Middle Column: Health Monitor */}
                    <div className="grid-column">
                        <HealthPanel resources={filteredResources} metrics={metrics} />
                    </div>

                    {/* Right Column: Chat + Alerts */}
                    <div className="grid-column">
                        <ChatPanel />
                        <AlertFeed alerts={alerts} />
                    </div>
                </div>
            </main>
        </div>
    );
}
